### ISSUE TITLE
VolView crash on windows/chrome requires restarting chrome

### ISSUE THREAD

**Issue by aylward** [KitwareMedical/VolView#227] opened 2022-11-09 14:28 UTC
Once VolView crashes on Windows Chrome, reloading the webpage and result in a VolView which doesn't display any images (rest of the app seems ok, but all render windows are blank).  It becomes necessary to restart chrome to get VoView working again.

**Comment by floryst** [comment] 2022-11-10 15:29
Closing as a duplicate of #197, as the crashes are related to volumetric scattering being enabled.

**Closed by floryst** 2022-11-10 15:29 UTC
Labels: bug, priority:P2
