### ISSUE TITLE
Clicking on 2D view degrades 3D rendering

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/VolView#194] opened 2022-10-26 16:13 UTC
Clicking on 2D view degrades 3D rendering. I think the 3D view pixelates for better performance during interaction (particularly visible when using larger dataset like **CTA chest**). But this should only happen when interacting with the 3D viewport.

**Comment by floryst** [comment] 2022-10-26 17:15
This is a duplicate of #175

**Closed by floryst** 2022-10-26 17:15 UTC
