### ISSUE TITLE
Document Dependencies in README.md or Equivalent

### ISSUE THREAD

**Issue by timthirion** [KitwareMedical/VolView#204] opened 2022-11-07 18:58 UTC
Before running the `npm install` step, I needed to install at least:
- pkg-config
- pixman
- cairo
- pango

And likely more, but it appears I'm stuck at a different step now. These would ideally be documented just before the instructions on how to build and run.

**Comment by floryst** [comment] 2022-11-07 20:36
Duplicate of #189. We'll use #189 to track documentation for developers.

**Closed by floryst** 2022-11-07 20:36 UTC
